In [40]:
import pandas as pd

df_hadis = pd.read_csv("Sunnah.csv")
df_hadis

,Perawi,Arab,Terjemahan
0,Hadits Abu Daud Nomor 1,حَدَّثَنَا عَبْدُ اللَّهِ بْنُ مَسْلَمَةَ بْنِ...,Telah menceritakan kepada kami [Abdullah bin M...
1,Hadits Abu Daud Nomor 2,حَدَّثَنَا مُسَدَّدُ بْنُ مُسَرْهَدٍ حَدَّثَنَ...,Telah menceritakan kepada kami [Musaddad bin M...
2,Hadits Abu Daud Nomor 3,حَدَّثَنَا مُوسَى بْنُ إِسْمَعِيلَ حَدَّثَنَا ...,Telah menceritakan kepada kami [Musa bin Isma'...
3,Hadits Abu Daud Nomor 4,حَدَّثَنَا مُسَدَّدُ بْنُ مُسَرْهَدٍ حَدَّثَنَ...,Telah menceritakan kepada kami [Musaddad bin M...
4,Hadits Abu Daud Nomor 5,حَدَّثَنَا عَمْرُو بْنُ مَرْزُوقٍ أَخْبَرَنَا ...,Telah menceritakan kepada kami [Amru bin Marzu...
...,...,...,...
38096,Hadits Tirmidzi Nomor 3888,حَدَّثَنَا بِشْرُ بْنُ آدَمَ ابْنُ ابْنَةِ أَز...,Telah menceritakan kepada kami [Bisyr bin Adam...
38097,Hadits Tirmidzi Nomor 3889,حَدَّثَنَا مُحَمَّدُ بْنُ بَشَّارٍ حَدَّثَنَا ...,Telah menceritakan kepada kami [Muhammad bin B...
38098,Hadits Tirmidzi Nomor 3890,حَدَّثَنَا مُحَمَّدُ بْنُ بَشَّارٍ حَدَّثَنَا ...,Telah menceritakan kepada kami [Muhammad bin B...
38099,NaN,NaN,NaN
38100,Hadits Tirmidzi Nomor 3891,حَدَّثَنَا هَارُونُ بْنُ مُوسَى بْنِ أَبِي عَل...,Telah menceritakan kepada kami [Harun bin Musa...

In [41]:
df_hadis = df_hadis.dropna(how='any',axis=0)
df_hadis = df_hadis.drop('Arab', axis=1)
df_hadis

,Perawi,Terjemahan
0,Hadits Abu Daud Nomor 1,Telah menceritakan kepada kami [Abdullah bin M...
1,Hadits Abu Daud Nomor 2,Telah menceritakan kepada kami [Musaddad bin M...
2,Hadits Abu Daud Nomor 3,Telah menceritakan kepada kami [Musa bin Isma'...
3,Hadits Abu Daud Nomor 4,Telah menceritakan kepada kami [Musaddad bin M...
4,Hadits Abu Daud Nomor 5,Telah menceritakan kepada kami [Amru bin Marzu...
...,...,...
38095,Hadits Tirmidzi Nomor 3887,Telah menceritakan kepada kami [Mahmud bin Gha...
38096,Hadits Tirmidzi Nomor 3888,Telah menceritakan kepada kami [Bisyr bin Adam...
38097,Hadits Tirmidzi Nomor 3889,Telah menceritakan kepada kami [Muhammad bin B...
38098,Hadits Tirmidzi Nomor 3890,Telah menceritakan kepada kami [Muhammad bin B...
38100,Hadits Tirmidzi Nomor 3891,Telah menceritakan kepada kami [Harun bin Musa...

In [42]:
df_bukhari = df_hadis.loc[8724:15361].reset_index()
df_bukhari

,index,Perawi,Terjemahan
0,8724,Hadits Bukhari Nomor 1,Telah menceritakan kepada kami [Al Humaidi Abd...
1,8725,Hadits Bukhari Nomor 2,Telah menceritakan kepada kami [Abdullah bin Y...
2,8726,Hadits Bukhari Nomor 3,Telah menceritakan kepada kami [Yahya bin Buka...
3,8727,Hadits Bukhari Nomor 4,Telah menceritakan kepada kami [Musa bin Isma'...
4,8728,Hadits Bukhari Nomor 5,Telah menceritakan kepada kami [Abdan] dia ber...
...,...,...,...
6633,15357,Hadits Bukhari Nomor 7004,Telah menceritakan kepada kami [Muhammad bin A...
6634,15358,Hadits Bukhari Nomor 7005,Telah menceritakan kepada kami [Hudbah bin Kha...
6635,15359,Hadits Bukhari Nomor 7006,Telah menceritakan kepada kami [Ali] telah men...
6636,15360,Hadits Bukhari Nomor 7007,Telah menceritakan kepada kami [Abu Nu'man] te...
6637,15361,Hadits Bukhari Nomor 7008,Telah menceritakan kepadaku [Ahmad bin Isykab]...

## Preproccess

#### Remove punctuation

In [43]:
import string
df_bukhari['Praproses'] = df_bukhari['Terjemahan'].str.replace('[{}]'.format(string.punctuation), '', regex=True)
df_bukhari.head()

,index,Perawi,Terjemahan,Praproses
0,8724,Hadits Bukhari Nomor 1,Telah menceritakan kepada kami [Al Humaidi Abd...,Telah menceritakan kepada kami Al Humaidi Abdu...
1,8725,Hadits Bukhari Nomor 2,Telah menceritakan kepada kami [Abdullah bin Y...,Telah menceritakan kepada kami Abdullah bin Yu...
2,8726,Hadits Bukhari Nomor 3,Telah menceritakan kepada kami [Yahya bin Buka...,Telah menceritakan kepada kami Yahya bin Bukai...
3,8727,Hadits Bukhari Nomor 4,Telah menceritakan kepada kami [Musa bin Isma'...,Telah menceritakan kepada kami Musa bin Ismail...
4,8728,Hadits Bukhari Nomor 5,Telah menceritakan kepada kami [Abdan] dia ber...,Telah menceritakan kepada kami Abdan dia berka...

#### Case folding

In [44]:
df_bukhari['Praproses'] = df_bukhari['Praproses'].str.lower()
df_bukhari.head()

,index,Perawi,Terjemahan,Praproses
0,8724,Hadits Bukhari Nomor 1,Telah menceritakan kepada kami [Al Humaidi Abd...,telah menceritakan kepada kami al humaidi abdu...
1,8725,Hadits Bukhari Nomor 2,Telah menceritakan kepada kami [Abdullah bin Y...,telah menceritakan kepada kami abdullah bin yu...
2,8726,Hadits Bukhari Nomor 3,Telah menceritakan kepada kami [Yahya bin Buka...,telah menceritakan kepada kami yahya bin bukai...
3,8727,Hadits Bukhari Nomor 4,Telah menceritakan kepada kami [Musa bin Isma'...,telah menceritakan kepada kami musa bin ismail...
4,8728,Hadits Bukhari Nomor 5,Telah menceritakan kepada kami [Abdan] dia ber...,telah menceritakan kepada kami abdan dia berka...

#### Stopwords removal

In [45]:
# !pip install Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stopwords = factory.get_stop_words()
stopwords = factory.create_stop_word_remover()

def stopwords_wrapper(text):
    return stopwords.remove(text)
df_bukhari['Praproses'] = df_bukhari['Praproses'].apply(stopwords_wrapper)
df_bukhari.head()

,index,Perawi,Terjemahan,Praproses
0,8724,Hadits Bukhari Nomor 1,Telah menceritakan kepada kami [Al Humaidi Abd...,menceritakan kami al humaidi abdullah bin az z...
1,8725,Hadits Bukhari Nomor 2,Telah menceritakan kepada kami [Abdullah bin Y...,menceritakan kami abdullah bin yusuf berkata m...
2,8726,Hadits Bukhari Nomor 3,Telah menceritakan kepada kami [Yahya bin Buka...,menceritakan kami yahya bin bukair berkata men...
3,8727,Hadits Bukhari Nomor 4,Telah menceritakan kepada kami [Musa bin Isma'...,menceritakan musa bin ismail berkata mencerita...
4,8728,Hadits Bukhari Nomor 5,Telah menceritakan kepada kami [Abdan] dia ber...,menceritakan abdan berkata mengabarkan kami ab...

#### Tokenization

In [46]:
# !pip install nltk
# import nltk
# nltk.download()

In [47]:
from nltk.tokenize import word_tokenize 

def word_tokenize_wrapper(text):
    return word_tokenize(text)

df_bukhari['Token'] = df_bukhari['Praproses'].apply(word_tokenize_wrapper)
df_bukhari.head()

,index,Perawi,Terjemahan,Praproses,Token
0,8724,Hadits Bukhari Nomor 1,Telah menceritakan kepada kami [Al Humaidi Abd...,menceritakan kami al humaidi abdullah bin az z...,"[menceritakan, kami, al, humaidi, abdullah, bi..."
1,8725,Hadits Bukhari Nomor 2,Telah menceritakan kepada kami [Abdullah bin Y...,menceritakan kami abdullah bin yusuf berkata m...,"[menceritakan, kami, abdullah, bin, yusuf, ber..."
2,8726,Hadits Bukhari Nomor 3,Telah menceritakan kepada kami [Yahya bin Buka...,menceritakan kami yahya bin bukair berkata men...,"[menceritakan, kami, yahya, bin, bukair, berka..."
3,8727,Hadits Bukhari Nomor 4,Telah menceritakan kepada kami [Musa bin Isma'...,menceritakan musa bin ismail berkata mencerita...,"[menceritakan, musa, bin, ismail, berkata, men..."
4,8728,Hadits Bukhari Nomor 5,Telah menceritakan kepada kami [Abdan] dia ber...,menceritakan abdan berkata mengabarkan kami ab...,"[menceritakan, abdan, berkata, mengabarkan, ka..."

#### POS tagging

In [48]:
# !pip install numpy
# !pip install python-crfsuite

In [49]:
from nltk.tag import CRFTagger
ct = CRFTagger()
ct.set_model_file('all_indo_man_tag_corpus_model.crf.tagger')
df_bukhari['POS tag'] = ct.tag_sents(df_bukhari['Token'])
df_bukhari['POS tag'].loc[0]

[('menceritakan', 'VB'),
 ('kami', 'PRP'),
 ('al', 'VB'),
 ('humaidi', 'NN'),
 ('abdullah', 'NN'),
 ('bin', 'NN'),
 ('az', 'NN'),
 ('zubair', 'NN'),
 ('berkata', 'VB'),
 ('menceritakan', 'VB'),
 ('kami', 'PRP'),
 ('sufyan', 'NN'),
 ('berkata', 'VB'),
 ('menceritakan', 'VB'),
 ('kami', 'PRP'),
 ('yahya', 'NN'),
 ('bin', 'FW'),
 ('said', 'FW'),
 ('al', 'FW'),
 ('anshari', 'VB'),
 ('berkata', 'NN'),
 ('telah', 'MD'),
 ('mengabarkan', 'VB'),
 ('kami', 'PRP'),
 ('muhammad', 'VB'),
 ('bin', 'NN'),
 ('ibrahim', 'NN'),
 ('at', 'NN'),
 ('taimi', 'NN'),
 ('pernah', 'MD'),
 ('mendengar', 'VB'),
 ('alqamah', 'NN'),
 ('bin', 'FW'),
 ('waqash', 'FW'),
 ('al', 'FW'),
 ('laitsi', 'NN'),
 ('berkata', 'NN'),
 ('pernah', 'MD'),
 ('mendengar', 'VB'),
 ('umar', 'NN'),
 ('bin', 'NN'),
 ('al', 'NN'),
 ('khaththab', 'NN'),
 ('diatas', 'NN'),
 ('mimbar', 'NN'),
 ('berkata', 'VB'),
 ('mendengar', 'VB'),
 ('rasulullah', 'NN'),
 ('shallallahu', 'VB'),
 ('alaihi', 'VB'),
 ('wasallam', 'NN'),
 ('bersabda', 'VB'),
 ('semua', 'CD'),
 ('perbuatan', 'NN'),
 ('tergantung', 'VB'),
 ('niatnya', 'NN'),
 ('balasan', 'NN'),
 ('tiaptiap', 'CD'),
 ('orang', 'NN'),
 ('tergantung', 'VB'),
 ('apa', 'WH'),
 ('diniatkan', 'VB'),
 ('barangsiapa', 'CD'),
 ('niat', 'NN'),
 ('hijrahnya', 'NN'),
 ('dunia', 'NN'),
 ('ingin', 'RB'),
 ('digapainya', 'RB'),
 ('karena', 'SC'),
 ('seorang', 'NND'),
 ('perempuan', 'NN'),
 ('ingin', 'RB'),
 ('dinikahinya', 'RB'),
 ('hijrahnya', 'RB'),
 ('kepada', 'IN'),
 ('apa', 'WH'),
 ('dia', 'PRP'),
 ('diniatkan', 'VB')]

In [53]:
df_bukhari['POS tag'].loc[df_bukhari['Terjemahan'].str.len().idxmin()]

[('jalur', 'NN'),
 ('periwayatan', 'NN'),
 ('sama', 'JJ'),
 ('hadits', 'NN'),
 ('sebelumnya', 'SC'),
 ('dari', 'IN'),
 ('abu', 'NN'),
 ('hurairah', 'NN'),
 ('allah', 'NN'),
 ('berfirman', 'NN'),
 ('berinfaklah', 'NN'),
 ('engkau', 'NN'),
 ('niscya', 'NN'),
 ('aku', 'NN'),
 ('memberi', 'VB'),
 ('infak', 'NN'),
 ('kepadamu', 'NN')]